### ISSUE TITLE
JSON encoding bug in json_prolog

### ISSUE THREAD

**Issue by daniel86** [knowrob/knowrob#150]
Test client for json_prolog:

    import roslib; roslib.load_manifest('json_prolog')
    import rospy
    from json_prolog import json_prolog
    if __name__ == '__main__':
        rospy.init_node('test_json_prolog')
        prolog = json_prolog.Prolog()
        query = prolog.query("X='{\"Y\": 847230894.4536E4}'.")
        for solution in query.solutions():
            print 'Found solution. X = %s' % (solution['X'])
        query.finish()

Output is:

    Found solution. X = {u'Y': 8472309000000.0}

Should be:

    Found solution. X = '{"Y": 847230894.4536E4}'

**Comment by ichumuh** [comment]
The loss in precision comes from a bug in json-lib:2.4. There exists a 6 year old bug report...
[https://sourceforge.net/p/json-lib/bugs/116/](https://sourceforge.net/p/json-lib/bugs/116/)
As mentioned in the comments the precision bug can be fixed by compiling against version 2.3.
I have tested it and it seems to be working.

However this does not change the fact that the result is a hashmap instead of a string.
The result is a hashmap because in JSONQuery.java encodeResult calls the put method from JSONObject which parses strings that have a json format.

**Comment by daniel86** [comment]
From JSONObject documentation:

- An extra , (comma) may appear just before the closing brace.
- Strings may be quoted with ' (single quote).
- Strings do not need to be quoted at all if they do not begin with a quote or single quote, and if they do not contain leading or trailing spaces, and if they do not contain any of these characters: { } [ ] / \ : , = ; # and if they do not look like numbers and if they are not the reserved words true, false, or null.
- Keys can be followed by = or => as well as by :.
- Values can be followed by ; (semicolon) as well as by , (comma).
- Numbers may have the 0- (octal) or 0x- (hex) prefix.
- Comments written in the slashshlash, slashstar, and hash conventions will be ignored.

Wrapping the value seems to fix the hashmap result bug without introducing new issues as far as I can see.

**Comment by daniel86** [comment]
Fixed by #151
