### ISSUE TITLE
KnowRob can't be started via roslaunch after Prolog update

### ISSUE THREAD

**Issue by benjaminalt** [knowrob/knowrob#310]
When starting KnowRob via `rosrun knowrob knowrob.launch`, it gets stuck in `urdf_init` (`has_kinematics_file` does not return). I could reproduce this with the current KnowRob master in a clean VM with nothing installed but ROS, Prolog and KnowRob.

This is "caused" by the Prolog update on 30. September, (version 8.2.4 --> 8.4.0, see https://launchpad.net/~swi-prolog/+archive/ubuntu/stable) which was automatically installed via the regular Ubuntu package updates. The old 8.2.4 version of Prolog can't be installed via the official PPA anymore, so I built it from source (https://www.swi-prolog.org/build/unix.html). When that version is used, the problem does not occur anymore --> **workaround: Building and installing swi-prolog 8.2.4 from source.**

Some things I noticed:

- Starting knowrob via `rosrun rosprolog rosprolog knowrob` works also with swi-prolog 8.4.0. It seems like running the ROS node makes the difference.
- It looks like the first `holds` statement in `has_kinematics_file` never unifies. swi-prolog constantly occupies one core on my machine and unification never finishes. When starting KnowRob with `rosrun rosprolog rosprolog knowrob` and manually invoking `has_kinematics_file`, it returns immediately.

**Comment by daniel86** [comment]
@benjaminalt thanks for the report. This is an odd error. I couldn't pinpoint the problem yet, but I will try to get it fixed asap

**Comment by sasjonge** [comment]
@daniel86 I could pinpoint the problem to this line of code:

https://github.com/knowrob/knowrob/blob/4d7af5484683cf2ff0aedd3b0126ae8c5077e035/src/utility/threads.pl#L204

If I set the time to a negative number, so that thread_get_message fails immediately if it doesn't get a message, KnowRob will start. Weirdly a number bigger than 0 will still result in an lock (the code will not step over this step in the given time). I'm at the moment not sure what the correct fix would be here (also I don't know how this changed by the updated Prolog version).

**Comment by sasjonge** [comment]
@benjaminalt This issue should be resolved by this PR: https://github.com/knowrob/knowrob/pull/315

It is just a hotfix and I created a new issue that is more specific to the general issue: https://github.com/knowrob/knowrob/issues/316
