### ISSUE TITLE
Is URDF2SRDL deprecated?

### ISSUE THREAD

**Issue by Aqudi** [knowrob/knowrob#329]
I'm trying to make a model of my robot using URDF2SRDL, but there is no file in master branch. 
Is it no longer used?

**Comment by Aqudi** [comment]
Thank you for your response.
Then, is there a way to replace URDF2SRDL?

**Comment by daniel86** [comment]
Hello. Have a look here: https://github.com/knowrob/knowrob/blob/master/launch/map.launch
It loads PR2 OWL file + URDF. Then you basically have kinematics from URDF plus components defined in the OWL file.
The whole SRDL ontology has not been aligned yet with the SOMA ontology used by KnowRob since some time, but it is high priority to work on capability modelling.

**Comment by Aqudi** [comment]
> Hello. Have a look here: https://github.com/knowrob/knowrob/blob/master/launch/map.launch It loads PR2 OWL file + URDF. Then you basically have kinematics from URDF plus components defined in the OWL file. The whole SRDL ontology has not been aligned yet with the SOMA ontology used by KnowRob since some time, but it is high priority to work on capability modelling.

Thank you!
