### ISSUE TITLE
Classpath of KnowRob packages that are loaded after JPL has been initialized is ignored

### ISSUE THREAD

**Issue by knowrob** [knowrob/knowrob#40]
KnowRob constructs the CLASSPATH environment variable by collecting entries stored in the classpath.txt files in each rosjava package in the dependencies. Usually, this is done at startup by the rosprolog script, but can also be done by the register_ros_package() predicate. 

The problem is that Java only considers the CLASSPATH variable once when the JVM is initialized, i.e. changes of this variable will have no effect once Java has been started. This may result in missing entries in the following startup sequence:
- rosprolog <some pkg>
- <start some Java component, e.g. visualization>
- register_ros_package(<some-pkg-with-Java-code>)
- call Java code in <some-pkg-with-Java-code>

Workaround:
Set up a 'demo package' that, for a given scenario, contains all required dependencies and loads them using its init.pl. Do not start Java code from the init.pl, but only after KnowRob has been loaded.

**Comment by daniel86** [comment]
I would suggest that we use a custom ClassLoader in knowrob to avoid this problem.

**Comment by daniel86** [comment]
Fixed with https://github.com/knowrob/knowrob/commit/4c49b7ed159309b078981fa7af04ef35adc29ca9 in indigo-devel branch.
I just changed it so that all generated classpath.txt files are handled when register_ros_package
is called the first time.
So at least one register_ros_package call must be made before Java code is called.
