### ISSUE TITLE
json_prolog seems to truncate floats when contained in lists

### ISSUE THREAD

**Issue by knowrob** [knowrob/knowrob#5]
While reading floats as normal variable bindings works well, they seem to be cast to integers when packed into lists.

**Comment by daniel86** [comment]
Fixed with https://github.com/knowrob/knowrob/commit/16d5873cf8726fce27d77b8fb850e68960d3bb47 and https://github.com/knowrob/knowrob/commit/3e27ffd4d66de383794dbdc3e6ff1cb7d968dd13 .
I had some precision troubles with json_prolog and timestamps because
float was used when the results were converted to JSON.
Switching to double fixed it. But it also happened for plain numbers not
only for numbers in lists.

This works now:
?- T1 = 1424291097.481, T2 = [1424291097.481].
T2 = [
 0 = 1424291097.481
]
T1 = 1424291097.481

Before switching to double this happened:
?- TimeAtom = '1424016422.136', atom_number(TimeAtom, Time).
Time = 1424016380
TimeAtom = 1424016422.136
